MAKEFLAGS += --silent

hello:
	gcc -ansi hello.c

fahr:
	gcc -ansi fahr.c

cels:
	gcc -ansi cels.c

fahr-for:
	gcc -ansi fahr-for.c

copy:
	gcc -ansi copy.c

charcount:
	gcc -ansi charcount.c

linecount:
	gcc -ansi linecount.c

blanks:
	gcc -ansi blanks.c

charsub:
	gcc -ansi charsub.c

run:
	./a.out

clean:
	rm *.out

win-run:
	./a.exe

win-clean:
	rm *.exe