MAKEFLAGS += --silent

datatypes:
	gcc -ansi datatypes.c

constants:
	gcc -ansi constants.c

longestline2:
	gcc -ansi longestline2.c

hextoint:
	gcc -ansi hextoint.c

squeeze:
	gcc -ansi squeeze.c

bitwise:
	gcc -ansi bitwise.c

assexp:
	gcc -ansi assexp.c

run:
	./a.out

clean:
	rm *.out

win-run:
	./a.exe

win-clean:
	rm *.exe