MAKEFLAGS += --silent

datatypes:
	gcc -ansi datatypes.c

constants:
	gcc -ansi constants.c

longestline2:
	gcc -ansi longestline2.c

run:
	./a.out

clean:
	rm *.out

win-run:
	./a.exe

win-clean:
	rm *.exe